// <auto-generated />
using System;
using System.Text.Json;
using FileUploader.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileUploader.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314201900_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileUploader.Data.InfectedFile", b =>
                {
                    b.Property<int>("InfectedFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InfectedFileId"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UploadVirusScanResultId")
                        .HasColumnType("integer");

                    b.Property<string>("VirusName")
                        .IsRequired()
                        .HasMaxLength(1048)
                        .HasColumnType("character varying(1048)");

                    b.HasKey("InfectedFileId");

                    b.HasIndex("UploadVirusScanResultId");

                    b.ToTable("InfectedFile");
                });

            modelBuilder.Entity("FileUploader.Data.Job", b =>
                {
                    b.Property<long>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("JobId"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockedBy")
                        .HasColumnType("text");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("JobId");

                    b.HasIndex("UserId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("FileUploader.Data.Upload", b =>
                {
                    b.Property<int>("UploadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UploadId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OrignalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PersistedObjectKey")
                        .HasColumnType("text");

                    b.Property<string>("TempObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UploadId");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Uploads");
                });

            modelBuilder.Entity("FileUploader.Data.UploadCandidate", b =>
                {
                    b.Property<int>("UploadCandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UploadCandidateId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ObjectFileKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("integer");

                    b.HasKey("UploadCandidateId");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("OwnerUserId");

                    b.ToTable("UploadCandidates");
                });

            modelBuilder.Entity("FileUploader.Data.UploadValidationError", b =>
                {
                    b.Property<int>("UploadValidationErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UploadValidationErrorId"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UploadId")
                        .HasColumnType("integer");

                    b.Property<string>("ValidationErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ValidationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UploadValidationErrorId");

                    b.HasIndex("UploadId");

                    b.ToTable("UploadValidationResults");
                });

            modelBuilder.Entity("FileUploader.Data.UploadVirusScanResult", b =>
                {
                    b.Property<int>("UploadVirusScanResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UploadVirusScanResultId"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawResult")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<int>("UploadId")
                        .HasColumnType("integer");

                    b.HasKey("UploadVirusScanResultId");

                    b.HasIndex("UploadId")
                        .IsUnique();

                    b.ToTable("UploadVirusScanResults");
                });

            modelBuilder.Entity("FileUploader.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Sub")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("UserId");

                    b.HasIndex("Sub")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FileUploader.Data.InfectedFile", b =>
                {
                    b.HasOne("FileUploader.Data.UploadVirusScanResult", "UploadVirusScanResult")
                        .WithMany("InfectedFiles")
                        .HasForeignKey("UploadVirusScanResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UploadVirusScanResult");
                });

            modelBuilder.Entity("FileUploader.Data.Job", b =>
                {
                    b.HasOne("FileUploader.Data.User", "User")
                        .WithMany("Jobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("FileUploader.Data.Upload", b =>
                {
                    b.HasOne("FileUploader.Data.User", "User")
                        .WithMany("Uploads")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FileUploader.Data.UploadCandidate", b =>
                {
                    b.HasOne("FileUploader.Data.User", "OwnerUser")
                        .WithMany("UploadCandidates")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("FileUploader.Data.UploadValidationError", b =>
                {
                    b.HasOne("FileUploader.Data.Upload", null)
                        .WithMany("UploadValidationErrors")
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FileUploader.Data.UploadVirusScanResult", b =>
                {
                    b.HasOne("FileUploader.Data.Upload", null)
                        .WithOne("UploadVirusScanResult")
                        .HasForeignKey("FileUploader.Data.UploadVirusScanResult", "UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FileUploader.Data.Upload", b =>
                {
                    b.Navigation("UploadValidationErrors");

                    b.Navigation("UploadVirusScanResult");
                });

            modelBuilder.Entity("FileUploader.Data.UploadVirusScanResult", b =>
                {
                    b.Navigation("InfectedFiles");
                });

            modelBuilder.Entity("FileUploader.Data.User", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("UploadCandidates");

                    b.Navigation("Uploads");
                });
#pragma warning restore 612, 618
        }
    }
}
